AZURE_LOCATION: 'centralus'
RESOURCE_NAME_PREFIX: 'apimdemo'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'apim-user'
ACCOUNT_NAME: 'https://dev.azure.com/mc97905a'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'